# Generated by Django 3.2.3 on 2021-05-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='user_name',
        ),
    ]
