# Generated by Django 3.2.3 on 2021-05-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_rename_name_test_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='TestDetail',
        ),
    ]
